### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by jmcomets** [k-team/KHome#1]
Tu fais du Java ? Parce que une class par fichier, le fichier ayant le même nom que la classe, ça y ressemble. C'est marqué [noir sur blanc](http://www.python.org/dev/peps/pep-0008/#package-and-module-names) qu'on nomme toujours les modules en minuscules et par ensemble de fonctionnalités

**Comment by TurpIF** [comment]
C'est corrigé. C'est vrai qu'en regardant l'arborescence ça me donnait des envies de vomir. Maintenant je sais pourquoi.
